### ISSUE TITLE
Unable to parse json! unable to decode byte 

### ISSUE THREAD

**Issue by glimchb** [DMTF/libredfish#108]
I'm running libredfish to one of DellEmc servers
On of the fields (SerialNumber) is gibberish - known bug, working with vendor to fix it.

See example here (using curl):
```
        "Status":       {
                "State":        "Enabled",
                "Health":       "OK"
        },
        "ChassisType":  "Enclosure",
        "IndicatorLED": "Off",
        "Manufacturer": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
        "Model":        "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
        "PartNumber":   "303-589-000A",
        "SerialNumber": "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒",
        "UUID": "ffffffff-ffff-ffff-ffff-ffffffffffff",
        "PowerState":   "On",
```

But libredfish returns **NOTHING** because json parsing failed on 1 field.

Expected behavior:
* escaping happens before json parsing (according to libjansson, there is full unicode support, see https://jansson.readthedocs.io/en/2.2/apiref.html#encoding)
* some kind of error returned (not just when compiled with DEBUG) why empty result returned

See example of debug output:
```
asyncHeaderCallback: Adding Connection => keep-alive to (nil)
asyncHeaderCallback: Adding OData-Version => 4.0 to 0x7fe594113e40
asyncHeaderCallback: Adding Cache-Control => no-cache to 0x7fe594113e40
asyncHeaderCallback: Adding Server => EMC-Redfish-Management to 0x7fe594113e40
asyncHeaderCallback: Adding Content-Length => 2708 to 0x7fe594113e40
asyncHeaderCallback: Adding Content-Type => application/json to 0x7fe594113e40
asyncHeaderCallback: Adding Allow => GET, PATCH to 0x7fe594113e40
rawAsyncWorkThread: Got response for url https://my-server/redfish/v1/Chassis/Chassis with code 200
createRedfishPayloadFromString: Unable to parse json! unable to decode byte 0xff near '"' UH\ufffd\ufffdH\ufffd\ufffd\ufffd
freeHeaders: Freeing 0x7fe594113330
freeHeaders: Freeing 0x7fe594113e40

```

**Comment by pboyd04** [comment]
I've put up a pull to return an error in this situation instead of just a NULL payload. If you think the library should return data then I would suggest opening an issue against libjansson as it is what is returning the error "unable to decode byte 0xff near '"' UH\ufffd\ufffdH\ufffd\ufffd\ufffd"
