### ISSUE TITLE
Support int64 in GetPayloadIntValue()

### ISSUE THREAD

**Issue by ZephyrYin** [DMTF/libredfish#125]
In file libredfish/src/payload.c, getPayloadIntValue() is casting json_int_t(long long) to int, which doesn't support read of large int, should we return fixed width of 64 instead? Or we need to add another getPayloadInt64Value() to read int64.

**Comment by ZephyrYin** [comment]
in file libredfish/src/payload.c

**Comment by pboyd04** [comment]
We should add a new function so as not to break backwards compatibility.

**Comment by ZephyrYin** [comment]
close issue as pull request is merged.
