### ISSUE TITLE
serviceDecRefAndWait is hanging while serviceDecRef() works, why?

### ISSUE THREAD

**Issue by pgondi7** [DMTF/libredfish#158]
Hi Team. We are using libredfish to create a program which is enumerating redfish service using createServiceEnumerator(). When function getPayloadByPath encounters an error with http response code 401 or 404, redfish service cleanup serviceDecRefAndWait() is hanging.  But when we use serviceDecRef() our program terminate normally even though getPayloadbyPath gets an error like 401 or 404. 

Question: What is the correct cleanup function for redfish service created using createServiceEnumerator()?

**Comment by mraineri** [comment]
@pboyd04 do you have any guidance for this?

**Comment by mraineri** [comment]
Closing; there hasn't been enough info provided to debug this further... If this is still an issue, we'd need to see debug logs to help trace the flow...
