### ISSUE TITLE
RedPaths referencing properties are returned as objects

### ISSUE THREAD

**Issue by dchanman** [DMTF/libredfish#159]
Hey Patrick,

My motivation for understanding this is to better define what RedPath should do if we were to standardize RedPath into a specification.

Just wanted to see if there was a particular reason why a RedPath terminating in a property would return an object rather than the raw JSON value:

```
$ ./redfishtest -H localhost:8000 /Chassis[0]/Status
{
  "Health": "OK",
  "HealthRollup": "OK",
  "State": "Enabled"
}

$ ./redfishtest -H localhost:8000 /Chassis[0]/Status/Health
{
  "Health": "OK"
}

$ ./redfishtest -H localhost:8000 /Chassis[0]/Status/Health/Health
{
  "Health": "OK"
}

$ ./redfishtest -H localhost:8000 /Chassis[0]/Status/Health/Health/Health
{
  "Health": "OK"
}

$ ./redfishtest -H localhost:8000 /Chassis[0]/Status/Health/Health/Health/Health
{
  "Health": "OK"
}
```

It leads to an interesting behaviour where a RedPath could repeatedly reference a property.

In my opinion, an alternate behaviour would look something like:

```
$ ./redfishtest -H localhost:8000 /Chassis[0]/Status
{
  "Health": "OK",
  "HealthRollup": "OK",
  "State": "Enabled"
}
$ echo $?
0

$ ./redfishtest -H localhost:8000 /Chassis[0]/Status/Health
"OK"
$ echo $?
0

$ ./redfishtest -H localhost:8000 /Chassis[0]/Status/Health/Health
$ echo $?
1
```

**Comment by pboyd04** [comment]
The rationale behind this was so that the C code interpreting the returned value didn't have to also guess at the type, it always gets and object. It simplified the code of callers greatly.

**Comment by dchanman** [comment]
Thanks for clarifying. We also discussed this two weeks ago at the regular meeting prior to releasing the RedPath spec for review and this isn't a behaviour we need to standardize into the v1.0.0 spec.
