### ISSUE TITLE
Unable to retrieve Systems members

### ISSUE THREAD

**Issue by martinkennelly** [DMTF/libredfish#27]
Hi,
I am currently not able to get members of the Systems endpoint (/v1/redfish/Systems/X). 

> {
  "@odata.context": "/redfish/v1/$metadata#Systems",
  "@odata.id": "/redfish/v1/Systems",
  "@odata.type": "#ComputerSystemCollection.ComputerSystemCollection",
  "Members@odata.count": 1,
  "Name": "Computer System Collection",
  "Members": {
    "@odata.id": "/redfish/v1/Systems/1"
  }
}

Tried command:

> ./redfishtest -u admin -p admin -W verdoc -H https://localhost:20000 /Systems[0]

It just hangs and does not return json. Iam using verdoc to skip version validation because I do not have access to /v1/ endpoint.

Retrieving Chassis members works as expected.

**Comment by pboyd04** [comment]
Can you enable debug during the build and then run the command with -vvvv to get the debug log so I can see what is going on?

To enable debug with cmake run this:
cmake -DCMAKE_BUILD_TYPE=Debug ..
make

**Comment by billdodd** [comment]
It looks like your "Members" array is not really an array. It should have square brackets like this:

```
    "Members": [
        {
            "@odata.id": "/redfish/v1/Systems/1"
        }
    ]
```

Though I'm not sure if that's what is causing the hang. The debug that @pboyd04 asked for should help confirm.

**Comment by pboyd04** [comment]
@billdodd Good catch.

**Comment by martinkennelly** [comment]
Here is the debug output:

> ./redfishtest -vvvv -u admin -p admin -W verdoc -H https://localhost:20000 /Systems[0]
addRequestHeader: Adding Accept => application/json to (nil)
addRequestHeader: Adding OData-Version => 4.0 to 0x55b8a9189f40
addRequestHeader: Adding User-Agent => libredfish to 0x55b8a9189f40
addRequestHeader: Adding Authorization => Basic YWRtaW46YWRtaW4= to 0x55b8a9189f40
asyncHeaderCallback: Adding Server => GoAhead-Webs to (nil)
asyncHeaderCallback: Adding Date => Thu Nov  5 13 to 0x7fedec090d30
asyncHeaderCallback: Adding Pragma => no-cache to 0x7fedec090d30
asyncHeaderCallback: Adding Cache-Control => no-cache to 0x7fedec090d30
asyncHeaderCallback: Adding Content-Type => application/json to 0x7fedec090d30
asyncHeaderCallback: Adding OData-Version => 4.0 to 0x7fedec090d30
rawAsyncWorkThread: Got response for url https://localhost:20000/redfish/v1 with code 200
addRequestHeader: Adding Accept => application/json to (nil)
addRequestHeader: Adding OData-Version => 4.0 to 0x7fedec036c60
addRequestHeader: Adding User-Agent => libredfish to 0x7fedec036c60
addRequestHeader: Adding Authorization => Basic YWRtaW46YWRtaW4= to 0x7fedec036c60
freeHeaders: Freeing 0x55b8a9189f40
freeHeaders: Freeing 0x7fedec090d30
asyncHeaderCallback: Adding Server => GoAhead-Webs to (nil)
asyncHeaderCallback: Adding Date => Thu Nov  5 13 to 0x7fedec0fe050
asyncHeaderCallback: Adding Pragma => no-cache to 0x7fedec0fe050
asyncHeaderCallback: Adding Cache-Control => no-cache to 0x7fedec0fe050
asyncHeaderCallback: Adding Content-Type => application/json to 0x7fedec0fe050
asyncHeaderCallback: Adding OData-Version => 4.0 to 0x7fedec0fe050
rawAsyncWorkThread: Got response for url https://localhost:20000/redfish/v1/Systems with code 200
addRequestHeader: Adding Accept => application/json to (nil)
addRequestHeader: Adding OData-Version => 4.0 to 0x7fedec0746d0
addRequestHeader: Adding User-Agent => libredfish to 0x7fedec0746d0
addRequestHeader: Adding Authorization => Basic YWRtaW46YWRtaW4= to 0x7fedec0746d0

Good spot, thank you Bill.

**Comment by pboyd04** [comment]
Ok, I'm going to close this issue as a service side issue.
