### ISSUE TITLE
Using [Id=x] hangs sometimes

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/libredfish#43]
I will upload good and hang example
[good.txt](https://github.com/DMTF/libredfish/files/2488890/good.txt)
[hang.txt](https://github.com/DMTF/libredfish/files/2488891/hang.txt)

Tested with FixRefCount branch

**Comment by pboyd04** [comment]
The new fix in FixRefCount, should fix this.

**Comment by jbobzin-insyde** [comment]
tested here and no hangs
