### ISSUE TITLE
-M PATCH hangs

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/libredfish#44]
[patch.txt](https://github.com/DMTF/libredfish/files/2488895/patch.txt)

**Comment by pboyd04** [comment]
The FixRefCount branch now contains a fix for this issue.

**Comment by jbobzin-insyde** [comment]
Confirm 
bin/redfishtest -H 192.168.0.104 -u root -p root -M PATCH /Systems[0]/IndicatorLED Blinking
Works correctly.
