### ISSUE TITLE
Is the callback in charge of freeing the payload when using getPayloadByPathAsync()?

### ISSUE THREAD

**Issue by aboczkox** [DMTF/libredfish#48]
Hi,

I would be grateful if someone can clarify if it's needed to free the payload (cleanupPayload) manually in the callback given to getPayloadByPathAsync().

Many thanks,
aboczkox

**Comment by pboyd04** [comment]
Yes, it is expected that the callback should free the payload, will ensure the Doxygen documentation makes that clear.
